name: Post Push

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
    - id: posts
      name: Detecting posts from the changes
      run: |
        i=0
        for changed_file in ${{ steps.files.outputs.added_modified }}; do
          echo "i am in `pwd`"
          echo "`ls -lrt`"
          echo "`cat ${changed_file}`"
          
          echo "Do something with ${changed_file}."
          if [[ "${changed_file}" == "content/posts/"* ]];
          then
            echo "File ${changed_file} matched post."
            echo "{post{i}}=${changed_file}" >> $GITHUB_OUTPUT
            ((i=i+1))
          fi
        done
    - if: steps.posts.outputs.post0
      name: Publish to medium
      uses: infraway/post-medium-action@v1.6.0
      with:
        access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
        markdown_file: ${{ steps.posts.outputs.post0 }}
        base_url: https://myblog.com
        post_url: https://myblog.com/posts
